import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import registerSetActiveClient from "./impl/clients/set-active-client.js";
import registerListClients from "./impl/clients/list-clients.js";
import registerGetClientCapabilities from "./impl/clients/get-client-capabilities.js";
import registerExecute from "./impl/execution/execute.js";
import registerExecuteFile from "./impl/execution/execute-file.js";
import registerGetScriptContent from "./impl/inspection/get-script-content.js";
import registerGetDataByCode from "./impl/inspection/get-data-by-code.js";
import registerGetConsoleOutput from "./impl/inspection/get-console-output.js";
import registerSearchInstances from "./impl/inspection/search-instances.js";
import registerScriptGrep from "./impl/inspection/script-grep.js";
import registerSemanticSearchScripts from "./impl/inspection/semantic-search-scripts.js";
import registerGetGameInfo from "./impl/inspection/get-game-info.js";
import registerGetDescendantsTree from "./impl/inspection/get-descendants-tree.js";
import registerClientScreenshot from "./impl/inspection/client-screenshot.js";
import registerGetPlayerState from "./impl/inspection/get-player-state.js";
import registerGetGameGuis from "./impl/inspection/get-game-guis.js";
import registerTraceGameActivity from "./impl/inspection/trace-game-activity.js";
import registerFindGameSystems from "./impl/inspection/find-game-systems.js";
import registerDecryptRemote from "./impl/inspection/decrypt-remote.js";
import registerRemoteSpy from "./impl/remote-spy/remote-spy.js";
import registerTypeTextBox from "./impl/gui/type-text-box.js";
import registerClickButton from "./impl/gui/click-button.js";
import registerScreenshotWindow from "./impl/windows/screenshot-window.js";
import registerListRobloxWindows from "./impl/windows/list-roblox-windows.js";
export function registerAllTools(server: McpServer): void {
    registerSetActiveClient(server);
    registerListClients(server);
    registerGetClientCapabilities(server);
    registerExecute(server);
    registerExecuteFile(server);
    registerGetScriptContent(server);
    registerGetDataByCode(server);
    registerGetConsoleOutput(server);
    registerSearchInstances(server);
    registerScriptGrep(server);
    registerSemanticSearchScripts(server);
    registerGetGameInfo(server);
    registerGetDescendantsTree(server);
    registerClientScreenshot(server);
    registerGetPlayerState(server);
    registerGetGameGuis(server);
    registerTraceGameActivity(server);
    registerFindGameSystems(server);
    registerDecryptRemote(server);
    registerRemoteSpy(server);
    registerTypeTextBox(server);
    registerClickButton(server);
    registerScreenshotWindow(server);
    registerListRobloxWindows(server);
}
